export const createPokemonData = (data) => {
  return {
    name: data["Name"],
    pokedexNumber: parseInt(data["Pokedex Number"]),
    imgName: parseInt(data["Img name"]),
    generation: data["Generation"],
    evolutionStage: data["Evolution Stage"],
    evolved: data["Evolved"],
    famili_ID: data["FamilyID"],
    croosGen: data["Cross Gen"],
    type_1: data["Type 1"],
    type_2: data["Type 2"],
    wether_1: data["Weather 1"],
    wether_2: data["Weather 2"],
    stat_total: data["STAT TOTAL"],
    atk: data["ATK"],
    def: data["DEF"],
    sta: data["STA"],
    legendary: data["Legendary"],
    aquireable: data["Aquireable"],
    spawns: data["Spawns"],
    regional: data["Regional"],
    raidable: data["Raidable"],
    hatchable: data["Hatchable"],
    shiny: data["Shiny"],
    nest: data["Nest"],
    new: data["New"],
    not_gettable: data["Not-Gettable"],
    future_evolve: data["Future Evolve"],
    '100%_cp_@40': data["100% CP @ 40"],
    '100%_cp_@39': data["100% CP @ 39"],
  };
};
